### ISSUE TITLE
SteamCMD download failiure

### ISSUE THREAD

**Issue by Yoruiopz** [faroukbmiled/BOIIIWD#34]
SteamCMD may fail to download a workshop map when downloading with error code (Failiure).

Can be reproduced by using BOIIIWD to download workshop map "Mori Rebirth"
https://steamcommunity.com/sharedfiles/filedetails/?id=2780964226

**Comment by faroukbmiled** [comment]
> ![image](https://private-user-images.githubusercontent.com/36910989/313256138-6c17729f-7c55-40de-9fdf-7cd6bb18d306.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA1MTg3MDEsIm5iZiI6MTcxMDUxODQwMSwicGF0aCI6Ii8zNjkxMDk4OS8zMTMyNTYxMzgtNmMxNzcyOWYtN2M1NS00MGRlLTlmZGYtN2NkNmJiMThkMzA2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDE2MDAwMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTEyZDk5NThlNzlkMWU1Zjg5ZGRkMTU5ZjExYTBkNjg2Y2RkYzg3YTNmMWU5ODdmMWVjOWQ1NTAwY2RmMzY3OWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.H-cnlNyVJ_1V_TD9vsG5AVYjFj9Y8C7KfFXzca-BVZQ) Latest Release

This has nothing to do with BOIIIWD, try going in settings and press "RESET SteamCMD" on the left, see if this resolves the issue! to note this will remove steamapps/workshop folder from SteamCMD's path

**Comment by Yoruiopz** [comment]
Reopening this issue as it has not been fixed. Resetting SteamCMD fixes it temporarily, but it is only a workaround. SteamCMD almost always fails to download a workshop item after resetting. This issue persists among multiple of my friends across the world, so it appears to be a problem on your side and not mine. I have provided all the necessary information to troubleshoot and find a solution.

**Comment by faroukbmiled** [comment]
> Reopening this issue as it has not been fixed. Resetting SteamCMD fixes it temporarily, but it is only a workaround. SteamCMD almost always fails to download a workshop item after the one downloaded after resetting. This issue persists among multiple of my friends across the world, so it appears to be a problem on your side and not mine. I have provided all the necessary information to troubleshoot and find a solution.

This issue will not be reopened. You can try manually downloading maps using SteamCMD on its own, and you'll encounter the same problem even without BOIIIWD. This issue is unrelated to BOIIIWD and won't be addressed further, as there is nothing I can do about it. Please note that "SteamCMD" is a separate Steam product/application that BOIIIWD interacts with, but it is not part of BOIIIWD itself.
