### ISSUE TITLE
"No internet connection" when I am connected to the internet

### ISSUE THREAD

**Issue by thicccpvpboi** [faroukbmiled/BOIIIWD#37]
Anytime that I attempt to download a mod, it always shows that I am not connected to the internet when I am. This only happens when attempting to download a mod, and didn't happen when it installed steamcmd for me. Attempting to run the program as an administrator didn't solve the issue. Trying previous versions of the mod didn't solve the issue. All of my filepaths are correct. Is there something that I am doing wrong? 
![image](https://github.com/faroukbmiled/BOIIIWD/assets/116120560/990e37e9-50a0-446a-8cf2-d0aabc54d7b2)

**Comment by faroukbmiled** [comment]
Please check latest release and let me know if it works out for you! -> #40

**Comment by thicccpvpboi** [comment]
I am testing it right now and it looks like it is frozen at loading when attempting to download. It is also frozen at loading when opening the library tab as well. I forgot to mention that the issue with the library tab was also happening in v0.3.5

**Comment by faroukbmiled** [comment]
> I am testing it right now and it looks like it is frozen at loading when attempting to download. It is also frozen at loading when opening the library tab as well. I forgot to mention that the issue with the library tab was also happening in v0.3.5

Im not too sure about the freezing,its normal for it to freeze for a little a bit since it will be running some checks or fetching ur folders for mods and maps, but if its taking too long it could be something else ,if u dont mind me asking what's ur cpu? Python is very slow depending on what cpu u have

**Comment by thicccpvpboi** [comment]
![image](https://github.com/faroukbmiled/BOIIIWD/assets/116120560/bcd26c87-28c0-45b6-b802-5ca5a46d1b4f)

**Comment by faroukbmiled** [comment]
> ![image](https://github.com/faroukbmiled/BOIIIWD/assets/116120560/bcd26c87-28c0-45b6-b802-5ca5a46d1b4f)
> 
> 

I can confirm that cpu should be fine
Next thing is how many mods/maps u have in total?

And i want you to go in settings turn on "Display SteamCMD console" and redownload again and show me what comes up in the console (or if its continuously crashing)

**Comment by thicccpvpboi** [comment]
I have 15 maps and 1 mod installed using steamcmd.
![image](https://github.com/faroukbmiled/BOIIIWD/assets/116120560/c1f34adb-955c-4b8a-9a26-0d5221253a65)
I have the display SteamCMD console option on and nothing pops up at all when clicking download. I also restarted the program and tried again and nothing shows up.
![image](https://github.com/faroukbmiled/BOIIIWD/assets/116120560/810b8f7c-7589-4dd3-969f-ac6e1dc4d03c)

**Comment by faroukbmiled** [comment]
> I have 15 maps and 1 mod installed using steamcmd. ![image](https://private-user-images.githubusercontent.com/116120560/337448765-c1f34adb-955c-4b8a-9a26-0d5221253a65.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MTA2NjYsIm5iZiI6MTcxNzcxMDM2NiwicGF0aCI6Ii8xMTYxMjA1NjAvMzM3NDQ4NzY1LWMxZjM0YWRiLTk1NWMtNGI4YS05YTI2LTBkNTIyMTI1M2E2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQyMTQ2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05ZDJkYjY4ZmVhOWNiZjIyYWI1NTI2NWY2OTJkY2ViZmRiMjM0MTY4NDY3Zjc3MGU2ZTdjNzMyYjZiYmNhODRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.oO5tBDuY8R9AxhyoNIaCJbVr6SVtjuCMSojYsXMp1Jw) I have the display SteamCMD console option on and nothing pops up at all when clicking download. I also restarted the program and tried again and nothing shows up. ![image](https://private-user-images.githubusercontent.com/116120560/337448633-810b8f7c-7589-4dd3-969f-ac6e1dc4d03c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc3MTA2NjYsIm5iZiI6MTcxNzcxMDM2NiwicGF0aCI6Ii8xMTYxMjA1NjAvMzM3NDQ4NjMzLTgxMGI4ZjdjLTc1ODktNGRkMy05NjlmLWFjNmUxZGM0ZDAzYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjA2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwNlQyMTQ2MDZaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04NTZlYjNiMTI1MTVkNzcxNWNlOGQ5MDRiNzRkMThiZDc2NzU2ODhkYjI0ZjU1NzkxYWY5NjcwYmU1MzYzOTNkJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.pmcufYEZ_-trcDf96cXI0IspHQBrh0Rr5o5pe8B4ffk)

Something is definitely wrong ,do you know how to clone a project and run it as a script using python?, that way we can see if anything is crashing inside the program itself (since we will have the console opened)?

If you could follow this:
Install python 3.12
Install git
Open a cmd prompt instance and type these commands:
```
git clone https://github.com/faroukbmiled/BOIIIWD.git
cd BOIIIWD
pip install -r .\requirements.txt
python boiiiwd_package\boiiiwd.py
```
This will run the program with the gui and also the console opened and if anything wrong happens you will see it in the console

If not i don't know how to assist you further than this

**Comment by thicccpvpboi** [comment]
Here are my cmd logs:
`Invalid geometry format: 920x560+85+-1
Invalid geometry format: 920x560+85+-2
Invalid geometry format: 920x560+86+-2
Invalid geometry format: 920x560+86+-3
Invalid geometry format: 920x560+86+-4
Invalid geometry format: 920x560+87+-4
Invalid geometry format: 920x560+87+-5
Invalid geometry format: 920x560+87+-6
Invalid geometry format: 920x560+88+-6
Invalid geometry format: 920x560+88+-7
Invalid geometry format: 920x560+88+-8
Invalid geometry format: 920x560+89+-8
Invalid geometry format: 920x560+89+-9
Invalid geometry format: 920x560+90+-9
Invalid geometry format: 920x560+90+-10
Invalid geometry format: 920x560+90+-11
Invalid geometry format: 920x560+91+-11
Invalid geometry format: 920x560+91+-12
Invalid geometry format: 920x560+91+-13
Invalid geometry format: 920x560+91+-14
Invalid geometry format: 920x560+91+-15
Invalid geometry format: 920x560+92+-15
Invalid geometry format: 920x560+92+-16
Invalid geometry format: 920x560+92+-17
Invalid geometry format: 920x560+92+-18
Invalid geometry format: 920x560+92+-17
Invalid geometry format: 920x560+92+-16
Invalid geometry format: 920x560+91+-16
Invalid geometry format: 920x560+91+-15
Invalid geometry format: 920x560+91+-14
Invalid geometry format: 920x560+91+-13
Invalid geometry format: 920x560+90+-13
Invalid geometry format: 920x560+90+-12
Invalid geometry format: 920x560+90+-11
Invalid geometry format: 920x560+90+-10
Invalid geometry format: 920x560+90+-9
Invalid geometry format: 920x560+90+-8
Invalid geometry format: 920x560+90+-7
Invalid geometry format: 920x560+89+-7
Invalid geometry format: 920x560+89+-6
Invalid geometry format: 920x560+89+-5
Invalid geometry format: 920x560+89+-4
Invalid geometry format: 920x560+89+-3
Invalid geometry format: 920x560+89+-2
Invalid geometry format: 920x560+89+-1
Exception in Tkinter callback
Traceback (most recent call last):
  File "Z:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "Z:\Users\marek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\games\blackops3\BOIIIWD\BOIIIWD\boiiiwd_package\src\main.py", line 414, in library_button_event
    self.show_library_widgets()
  File "C:\games\blackops3\BOIIIWD\BOIIIWD\boiiiwd_package\src\main.py", line 373, in show_library_widgets
    status = self.library_tab.load_items(self.settings_tab.edit_destination_folder.get())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\games\blackops3\BOIIIWD\BOIIIWD\boiiiwd_package\src\library_tab.py", line 270, in load_items
    workshop_id = extract_json_data(json_path, "PublisherID") or "None"
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\games\blackops3\BOIIIWD\BOIIIWD\boiiiwd_package\src\helpers.py", line 247, in extract_json_data
    data = json.load(json_file)
           ^^^^^^^^^^^^^^^^^^^^
  File "Z:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 299: character maps to <undefined>
Exception in Tkinter callback
Traceback (most recent call last):
  File "Z:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1967, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "Z:\Users\marek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked
    self._command()
  File "C:\games\blackops3\BOIIIWD\BOIIIWD\boiiiwd_package\src\helpers.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\games\blackops3\BOIIIWD\BOIIIWD\boiiiwd_package\src\main.py", line 1100, in download_map
    self.library_tab.load_items(self.settings_tab.edit_destination_folder.get(), dont_add=True)
  File "C:\games\blackops3\BOIIIWD\BOIIIWD\boiiiwd_package\src\library_tab.py", line 270, in load_items
    workshop_id = extract_json_data(json_path, "PublisherID") or "None"
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\games\blackops3\BOIIIWD\BOIIIWD\boiiiwd_package\src\helpers.py", line 247, in extract_json_data
    data = json.load(json_file)
           ^^^^^^^^^^^^^^^^^^^^
  File "Z:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 299: character maps to <undefined>
`

**Comment by faroukbmiled** [comment]
> Here are my cmd logs: `Invalid geometry format: 920x560+85+-1 Invalid geometry format: 920x560+85+-2 Invalid geometry format: 920x560+86+-2 Invalid geometry format: 920x560+86+-3 Invalid geometry format: 920x560+86+-4 Invalid geometry format: 920x560+87+-4 Invalid geometry format: 920x560+87+-5 Invalid geometry format: 920x560+87+-6 Invalid geometry format: 920x560+88+-6 Invalid geometry format: 920x560+88+-7 Invalid geometry format: 920x560+88+-8 Invalid geometry format: 920x560+89+-8 Invalid geometry format: 920x560+89+-9 Invalid geometry format: 920x560+90+-9 Invalid geometry format: 920x560+90+-10 Invalid geometry format: 920x560+90+-11 Invalid geometry format: 920x560+91+-11 Invalid geometry format: 920x560+91+-12 Invalid geometry format: 920x560+91+-13 Invalid geometry format: 920x560+91+-14 Invalid geometry format: 920x560+91+-15 Invalid geometry format: 920x560+92+-15 Invalid geometry format: 920x560+92+-16 Invalid geometry format: 920x560+92+-17 Invalid geometry format: 920x560+92+-18 Invalid geometry format: 920x560+92+-17 Invalid geometry format: 920x560+92+-16 Invalid geometry format: 920x560+91+-16 Invalid geometry format: 920x560+91+-15 Invalid geometry format: 920x560+91+-14 Invalid geometry format: 920x560+91+-13 Invalid geometry format: 920x560+90+-13 Invalid geometry format: 920x560+90+-12 Invalid geometry format: 920x560+90+-11 Invalid geometry format: 920x560+90+-10 Invalid geometry format: 920x560+90+-9 Invalid geometry format: 920x560+90+-8 Invalid geometry format: 920x560+90+-7 Invalid geometry format: 920x560+89+-7 Invalid geometry format: 920x560+89+-6 Invalid geometry format: 920x560+89+-5 Invalid geometry format: 920x560+89+-4 Invalid geometry format: 920x560+89+-3 Invalid geometry format: 920x560+89+-2 Invalid geometry format: 920x560+89+-1 Exception in Tkinter callback Traceback (most recent call last): File "Z:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1967, in __call__ return self.func(*args) ^^^^^^^^^^^^^^^^ File "Z:\Users\marek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked self._command() File "C:\games\blackops3\BOIIIWD\BOIIIWD\boiiiwd_package\src\main.py", line 414, in library_button_event self.show_library_widgets() File "C:\games\blackops3\BOIIIWD\BOIIIWD\boiiiwd_package\src\main.py", line 373, in show_library_widgets status = self.library_tab.load_items(self.settings_tab.edit_destination_folder.get()) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\games\blackops3\BOIIIWD\BOIIIWD\boiiiwd_package\src\library_tab.py", line 270, in load_items workshop_id = extract_json_data(json_path, "PublisherID") or "None" ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\games\blackops3\BOIIIWD\BOIIIWD\boiiiwd_package\src\helpers.py", line 247, in extract_json_data data = json.load(json_file) ^^^^^^^^^^^^^^^^^^^^ File "Z:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode return codecs.charmap_decode(input,self.errors,decoding_table)[0] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 299: character maps to <undefined> Exception in Tkinter callback Traceback (most recent call last): File "Z:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\tkinter\__init__.py", line 1967, in __call__ return self.func(*args) ^^^^^^^^^^^^^^^^ File "Z:\Users\marek\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\customtkinter\windows\widgets\ctk_button.py", line 554, in _clicked self._command() File "C:\games\blackops3\BOIIIWD\BOIIIWD\boiiiwd_package\src\helpers.py", line 103, in wrapper return func(*args, **kwargs) ^^^^^^^^^^^^^^^^^^^^^ File "C:\games\blackops3\BOIIIWD\BOIIIWD\boiiiwd_package\src\main.py", line 1100, in download_map self.library_tab.load_items(self.settings_tab.edit_destination_folder.get(), dont_add=True) File "C:\games\blackops3\BOIIIWD\BOIIIWD\boiiiwd_package\src\library_tab.py", line 270, in load_items workshop_id = extract_json_data(json_path, "PublisherID") or "None" ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "C:\games\blackops3\BOIIIWD\BOIIIWD\boiiiwd_package\src\helpers.py", line 247, in extract_json_data data = json.load(json_file) ^^^^^^^^^^^^^^^^^^^^ File "Z:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1008.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 23, in decode return codecs.charmap_decode(input,self.errors,decoding_table)[0] ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 299: character maps to <undefined> `

This happened when you ran the program or when you pressed something? like download of library?

**Comment by thicccpvpboi** [comment]
The new build works! Thank you so much!

**Comment by faroukbmiled** [comment]
> The new build works! Thank you so much!

No problem,thank you for helping me figuring this out
