### ISSUE TITLE
Waiting for steamcmd...

### ISSUE THREAD

**Issue by Lunafyy** [faroukbmiled/BOIIIWD#47]
The downloader was working perfectly up until today where it keeps flickering between "Waiting for steamcmd..." and "Network Speed: " every second or so. Fixed it temporarily by deleting all files related to BOIIIWD and reinstalling it, but this only worked for 1 download before repeating the same behaviour. Antivirus is disabled and this behaviour is persistent even after a reinstall.

**Comment by Spired111** [comment]
having the same problem when using batch downloader. tried downloading, only worked for one item then had the problem. tried dowloading using the single item downloader, still having same problem.

**Comment by faroukbmiled** [comment]
> Please show me a screenshot of the said behavior, i want to see if the failure count is going up, and also make sure to turn "console on" in settings and redownload the maps ,let me know exactly what happens looking at the console or if its simply crashing, if it is this issue is related to steamcmd being unstable as usual and nothing i can do about it, BOIIIWD is a wrapper around the steamcmd executable and tries to make it more stable.

The only thing you can really do to "fix this", is going into settings and pressing "Reset SteamCMD" from the right sidebar, this is a temporary fix obviously since that issue is baked into Steamcmd for some reason

**Comment by faroukbmiled** [comment]
If you have this issue ,please use latest version ,use login and turn on "Display Cosnole", and report with details from console and the overall behavior here (screenshots are welcome)

**Comment by JorNiebla** [comment]
I can consistently get this error by having spaces on the path, the initialization works, it downloads and configure steamcmd correctly, after selecting the game folder and trying to download any map an exception is thrown.

![imagen](https://github.com/user-attachments/assets/db484fb1-660d-4bc6-8f23-98a3fe8840d5)

**Comment by faroukbmiled** [comment]
> I can consistently get this error by having spaces on the path, the initialization works, it downloads and configure steamcmd correctly, after selecting the game folder and trying to download any map an exception is thrown.
> 
> ![imagen](https://private-user-images.githubusercontent.com/58117550/351537966-db484fb1-660d-4bc6-8f23-98a3fe8840d5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE4MjE3NzIsIm5iZiI6MTcyMTgyMTQ3MiwicGF0aCI6Ii81ODExNzU1MC8zNTE1Mzc5NjYtZGI0ODRmYjEtNjYwZC00YmM2LThmMjMtOThhM2ZlODg0MGQ1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI0VDExNDQzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgzODI3ZmQzYTg2MTlmNWZkYmYwNmI1OTY5OTg5NmViNzgwNGNlNDZhY2IwMWQwMzIzN2JkMTBjY2ZiYjY1NzkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.5DASQLLh5lCLJinuP3nxyl6jV1caDX2F56qbowOZ8Uc)

Hmm that's really weird ,do u mind sharing the full path where the steamcmd executable is at? (remove your username from the path)
I will try to recreate this and work on it
