### ISSUE TITLE
wont update 

### ISSUE THREAD

**Issue by aimovr** [faroukbmiled/BOIIIWD#62]
whenever i go yo update the workshop downloader it says error installing the update binary mode doesnt take an errors argument and wont update

**Comment by faroukbmiled** [comment]
> whenever i go yo update the workshop downloader it says error installing the update binary mode doesnt take an errors argument and wont update 

The updater was broken in some older versions, this has been fixed since v0.3.7.1, in your case you gotta manually update to [this](https://github.com/faroukbmiled/BOIIIWD/releases/latest) just this time, sorry for the inconvenience
