### ISSUE TITLE
Crashing Upon Launch

### ISSUE THREAD

**Issue by Astroescy** [faroukbmiled/BOIIIWD#65]
I downloaded the Blood Run Mod and now every time I try opening boiii it opens with a black screen and after a few seconds it closes. I've removed all mods and maps and reset steamcmd and still same issue.

**Comment by faroukbmiled** [comment]
Are you sure it isn't your antivirus/defender interfering with the process? ,that sounds like it to me, if you haven't fixed this issue yet, reply to this and i will tell you what to do to debug it further so i know what's causing this behavior

**Comment by Astroescy** [comment]
Apologies. It seems to be more of a boiii issue, after deleting the exe and re-adding it into the folder the game launches normally.
