### ISSUE TITLE
Does not support hidden workshop items

### ISSUE THREAD

**Issue by dzkm** [faroukbmiled/BOIIIWD#68]
Mods like [[Mod] Ultimate Experience/Leveling Mod [V188.5]](https://steamcommunity.com/sharedfiles/filedetails/?id=2942053577) aren't supported by the tool since they're hidden, but not private. 

To replicate:
1. Open BOIIIWD
2. Setup your steamcmd correctly
3. Try downloading the above workshop item using the `Download` button
4. See the message where the item is invalid

Funny enough, the `Details` button can bring the item's information correctly.
SteamCMD can and will download hidden workshop items:
![image](https://github.com/user-attachments/assets/dbaca296-ff54-4d35-8f4a-305eae0f02b8)

**Comment by faroukbmiled** [comment]
Sorry for the inconvenience ,there is an option in settings called "Skip invalid items", turn that off and try again then let me know
Its an option since some mods when hidden for example it doesn't have the correct api info for updating and such ,those invalid items cant be checked for updates from boiiiwd
![image](https://github.com/user-attachments/assets/db682ebf-489b-48aa-8cc8-1306546ba5a0)

**Comment by dzkm** [comment]
No luck. Here's a video proof with the console right by its side:

https://github.com/user-attachments/assets/987cb6e8-0a45-477f-86a8-c61610244347

**Comment by faroukbmiled** [comment]
Okay i wads 

> No luck. Here's a video proof with the console right by its side:
> 
>  BOIIIWD_wkByosZCuJ.mp4


That same map is downloading just fine for me check screenshot, make sure to press "Save" in settings after toggling off "Skip invalid items"


![image](https://github.com/user-attachments/assets/2adb7c3b-a308-4b68-b4eb-56d1c33fa495)


Or open the "config.ini" in the root folder where BOIIIWD.exe is at ,and change skip_invalid to off (settings toggle does this)


![image](https://github.com/user-attachments/assets/53b2339f-e518-4d27-983e-d1629a91a1c8)

**Comment by dzkm** [comment]
After clicking `Save` in the settings, apparently the issue has been resolved. 
As a developer myself, I'd recommend making the settings menu event-driven or have a pop-up about unsaved settings.

**Comment by faroukbmiled** [comment]
> After clicking `Save` in the settings, apparently the issue has been resolved. As a developer myself, I'd recommend making the settings menu event-driven or have a pop-up about unsaved settings.

I've implemented auto save for some settings, but not all. Honestly, the entire settings tab needs a complete rewrite, but I haven't found the time to do it yet, thank you for the suggestion!
